config/routes.rb
JoinASquad::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    root :to => 'home#index'
  end

  resources :users
  resources :games

  # aliases
  get 'profile' => 'users#index'

  get 'home' => redirect('/') 
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
    user ||= User.new

    can :read, Game
    can :read, User

    if user.admin?
      can :read, :all
      can :manage, Game
    else
      if user.persisted?
        can :manage, user
      end
    end
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :user_games
  has_many :users, :through => :user_games

  attr_accessible :name

  validates :name, :presence => true, :uniqueness => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :remember_me

  has_many :user_games
  has_many :games, :through => :user_games

  def admin?
    !!self.admin
  end
end

app/models/user_game.rb
class UserGame < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_persistent_user_cookie
  protect_from_forgery

protected

  def set_persistent_user_cookie
    cookies['last_user_signed_in'] = current_user.email if user_signed_in?
  end
end

app/controllers/games_controller.rb
class GamesController < ResourcesController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Devise::Controllers::InternalHelpers

  def index
    resource = build_resource
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  check_authorization
  load_and_authorize_resource

  rescue_from CanCan::AccessDenied do |exception|
    if user_signed_in?
      redirect_to root_path, :alert => exception.message
    else
      warden.authenticate!(:scope => :user)
    end
  end

  respond_to :html

  def create
    resource.save
    respond_with resource
  end

  def destroy
    flash[:notice] = 'Successfully deleted.' if resource.destroy
    respond_with resource
  end

  protected

  def resource
    instance_variable_get(instance_variable_name)
  end

  # This works mostly by accident and is hard to test. Fortunately, if it breaks
  # it will break damn near everything.
  def instance_variable_name
    "@#{self.class.name.sub("Controller", "").underscore.split('/').last.singularize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ResourcesController
  before_filter :authenticate_user!, :only => :index
  before_filter :redirect_if_not_user_manager, :only => :index

  respond_to :html

  def index
    authorize! :read, User
    @users = User.all
  end

  def show
    @user = User.find params[:id]
    authorize! :read, @user
  end

  def edit
    @user = User.find params[:id]
    authorize! :manage, @user
  end

  def update
    @user = User.find params[:id]
    authorize! :manage, @user
    if @user.update_attributes(params[:user])
      flash[:notice] = 'User profile updated successfully.'
    end
    respond_with(@user, :location => @user)
  end

  protected

  def redirect_if_not_user_manager
    redirect_to current_user unless can?(:manage, User)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def signed_in_before?
    cookies['last_user_signed_in']
  end
end

app/views/games/_form.html.haml
= simple_form_for @game do |f|
  = f.error_notification
  %fieldset
    .inputs
      = f.input :name
    .form-actions
      = f.button :submit, "Create game", :class => 'btn large primary'

app/views/games/index.html.haml
.fluid-sidebar
  %h1 Games
.fluid-content
  %ul
    - @games.each do |game|
      %li= link_to game.name, game
  - if can? :manage, Game
    = link_to 'Add game', new_game_path

app/views/games/show.html.haml
.fluid-sidebar
  = link_to 'Games', games_path
.fluid-content
  %h1= @game.name
  = link_to 'Delete game', @game, :method => :delete

app/views/home/index.html.haml
#home
  .fluid-sidebar
    %h1 Find friends. Play together.
    :markdown
      Welcome to _joinasquad.com_, a service built to help gamers find other gamers.
  .fluid-content
    %ul.tabs.nav
      - if user_signed_in?
        %li
          %a(href="/getting-started" data-toggle="tab" data-target="#getting-started") Getting started
      - else
        %li(class="#{'active' if request.path == new_user_session_path || request.path == '/'}")
          %a(href="/login" data-toggle="tab" data-target="#login") Login
        %li(class="#{'active' if request.path == new_user_registration_path}")
          %a(data-toggle="tab" data-target="#join"){:href => new_user_registration_path} Join
      %li
        %a(href="/about" data-toggle="tab" data-target="#about") About
    .tab-content
      - if user_signed_in?
        #getting-started.tab-pane(name="getting-started")
          :markdown
            To get started, please fill in some basic profile information.
      - else
        #login.tab-pane(name="login" class="#{'active' if request.path == new_user_session_path || request.path == '/'}")
          = render :partial => 'devise/sessions/form'
        #join.tab-pane(name="join" class="#{'active' if request.path == new_user_registration_path}")
          = render :partial => 'devise/registrations/form'
      #about.tab-pane(name="about")
        %h2 About us
        :markdown
          I built _joinasquad.com_ because gaming is always better with a wingman or wingwoman.

          The premise of the site is simple. If you want to find someone to play a game with, mark it down on your profile and check out people with similar interests.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title joinasquad.com: Let's play together
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %a(href="http://github.com/cairo140/joinasquad.com")
      %img(src="https://a248.e.akamai.net/assets.github.com/img/4c7dc970b89fd04b81c8e221ba88ff99a06c6b61/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f77686974655f6666666666662e706e67" alt="Fork me on GitHub" id="fork_me_on_github")
    %nav.navbar.navbar-fixed-top
      .navbar-inner
        .fluid-container.sidebar-left
          .logo-container.fluid-sidebar
            %h1#logo
              %a{:href => root_path}
                ! <span class="white">joinasquad</span><span class="yellow">.</span><span class="white">com</span>
          %ul.nav.fluid-content
            %li= link_to 'Home', root_path
            %li= link_to 'Games', games_path
            - if user_signed_in?
              %li= link_to('Profile', current_user)
              %li= link_to('Logout', destroy_user_session_path, :method => :delete)
    %section#notifications
      .fluid-container
        - unless alert.nil?
          .alert.alert-error= alert
        - unless notice.nil?
          .alert= notice
    %section#content
      .fluid-container.sidebar-left
        = yield

app/views/resources/new.html.haml
.fluid-content
  = render :partial => 'form'

app/views/users/edit.html.haml
.container
  %h1 Edit #{@user.email}
  = simple_form_for @user do |f|
    = f.input :email
    .actions
      = f.button :submit

app/views/users/show.html.haml
#user.fluid-content{'data-id' => @user.id, 'data-type' => User}
  - if can? :write, @user
    = link_to 'Edit', [:edit, @user]
  %h1= @user.email
  %section
    %h2 Games
    - @user.games.each do |game|
      = game.name